// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Face represents a detected face with its properties
 */
export class Face {
    /**
     * Rectangle for face bounds
     */
    "BoundingBox": RectF;

    /**
     * 5 facial landmark points
     */
    "Landmarks": PointF[];
    "Confidence": number;

    /** Creates a new Face instance. */
    constructor($$source: Partial<Face> = {}) {
        if (!("BoundingBox" in $$source)) {
            this["BoundingBox"] = (new RectF());
        }
        if (!("Landmarks" in $$source)) {
            this["Landmarks"] = Array.from({ length: 5 }, () => (new PointF()));
        }
        if (!("Confidence" in $$source)) {
            this["Confidence"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Face instance from a string or object.
     */
    static createFrom($$source: any = {}): Face {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("BoundingBox" in $$parsedSource) {
            $$parsedSource["BoundingBox"] = $$createField0_0($$parsedSource["BoundingBox"]);
        }
        if ("Landmarks" in $$parsedSource) {
            $$parsedSource["Landmarks"] = $$createField1_0($$parsedSource["Landmarks"]);
        }
        return new Face($$parsedSource as Partial<Face>);
    }
}

/**
 * PointF represents a point with float64 coordinates
 */
export class PointF {
    "X": number;
    "Y": number;

    /** Creates a new PointF instance. */
    constructor($$source: Partial<PointF> = {}) {
        if (!("X" in $$source)) {
            this["X"] = 0;
        }
        if (!("Y" in $$source)) {
            this["Y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PointF instance from a string or object.
     */
    static createFrom($$source: any = {}): PointF {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PointF($$parsedSource as Partial<PointF>);
    }
}

/**
 * RectF represents a rectangle with PointF coordinates
 */
export class RectF {
    "Min": PointF;
    "Max": PointF;

    /** Creates a new RectF instance. */
    constructor($$source: Partial<RectF> = {}) {
        if (!("Min" in $$source)) {
            this["Min"] = (new PointF());
        }
        if (!("Max" in $$source)) {
            this["Max"] = (new PointF());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RectF instance from a string or object.
     */
    static createFrom($$source: any = {}): RectF {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Min" in $$parsedSource) {
            $$parsedSource["Min"] = $$createField0_0($$parsedSource["Min"]);
        }
        if ("Max" in $$parsedSource) {
            $$parsedSource["Max"] = $$createField1_0($$parsedSource["Max"]);
        }
        return new RectF($$parsedSource as Partial<RectF>);
    }
}

// Private type creation functions
const $$createType0 = RectF.createFrom;
const $$createType1 = PointF.createFrom;
const $$createType2 = $Create.Array($$createType1);
