// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DialogFile {
    "Path": string;
    "Hash": string;
    "Dimensions": number[];
    "Extension": string;
    "Size": number;

    /** Creates a new DialogFile instance. */
    constructor($$source: Partial<DialogFile> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Hash" in $$source)) {
            this["Hash"] = "";
        }
        if (!("Dimensions" in $$source)) {
            this["Dimensions"] = [];
        }
        if (!("Extension" in $$source)) {
            this["Extension"] = "";
        }
        if (!("Size" in $$source)) {
            this["Size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DialogFile instance from a string or object.
     */
    static createFrom($$source: any = {}): DialogFile {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Dimensions" in $$parsedSource) {
            $$parsedSource["Dimensions"] = $$createField2_0($$parsedSource["Dimensions"]);
        }
        return new DialogFile($$parsedSource as Partial<DialogFile>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
