// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as detection$0 from "../../github.com/vegidio/open-photo-ai/models/detection/models.js";

/**
 * CropInfo is the per-file flip/rotate/crop the user applied in the Crop/Rotate modal. It is applied to the source image
 * (flip → rotate → crop) before any enhancement runs. A zero value (Width <= 0 || Height <= 0) means "no crop".
 */
export class CropInfo {
    "Rotation": number;
    "FlipH": boolean;
    "FlipV": boolean;
    "Top": number;
    "Left": number;
    "Width": number;
    "Height": number;

    /** Creates a new CropInfo instance. */
    constructor($$source: Partial<CropInfo> = {}) {
        if (!("Rotation" in $$source)) {
            this["Rotation"] = 0;
        }
        if (!("FlipH" in $$source)) {
            this["FlipH"] = false;
        }
        if (!("FlipV" in $$source)) {
            this["FlipV"] = false;
        }
        if (!("Top" in $$source)) {
            this["Top"] = 0;
        }
        if (!("Left" in $$source)) {
            this["Left"] = 0;
        }
        if (!("Width" in $$source)) {
            this["Width"] = 0;
        }
        if (!("Height" in $$source)) {
            this["Height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CropInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CropInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CropInfo($$parsedSource as Partial<CropInfo>);
    }
}

export class File {
    "Path": string;
    "Hash": string;
    "Dimensions": number[];
    "Extension": string;
    "Size": number;

    /** Creates a new File instance. */
    constructor($$source: Partial<File> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Hash" in $$source)) {
            this["Hash"] = "";
        }
        if (!("Dimensions" in $$source)) {
            this["Dimensions"] = [];
        }
        if (!("Extension" in $$source)) {
            this["Extension"] = "";
        }
        if (!("Size" in $$source)) {
            this["Size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new File instance from a string or object.
     */
    static createFrom($$source: any = {}): File {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Dimensions" in $$parsedSource) {
            $$parsedSource["Dimensions"] = $$createField2_0($$parsedSource["Dimensions"]);
        }
        return new File($$parsedSource as Partial<File>);
    }
}

/**
 * InferenceParams carries the extra, per-operation inputs the frontend supplies to ProcessImage/ExportImage alongside
 * the operation IDs. It is an extensible bag: new per-operation inputs (e.g. masks, palettes) are added as fields here
 * without changing the service method signatures. A struct (rather than a map[string]any) keeps Wails' typed
 * marshaling intact across the JS↔Go boundary.
 */
export class InferenceParams {
    /**
     * Faces are the pre-detected faces forwarded to the face-recovery operations (athens/santorini).
     */
    "Faces": detection$0.Face[];

    /**
     * Crop is the flip/rotate/crop applied to the source image before any enhancement. A zero value means "no crop".
     */
    "Crop": CropInfo;

    /** Creates a new InferenceParams instance. */
    constructor($$source: Partial<InferenceParams> = {}) {
        if (!("Faces" in $$source)) {
            this["Faces"] = [];
        }
        if (!("Crop" in $$source)) {
            this["Crop"] = (new CropInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InferenceParams instance from a string or object.
     */
    static createFrom($$source: any = {}): InferenceParams {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Faces" in $$parsedSource) {
            $$parsedSource["Faces"] = $$createField0_0($$parsedSource["Faces"]);
        }
        if ("Crop" in $$parsedSource) {
            $$parsedSource["Crop"] = $$createField1_0($$parsedSource["Crop"]);
        }
        return new InferenceParams($$parsedSource as Partial<InferenceParams>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = detection$0.Face.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = CropInfo.createFrom;
