version: '3'

tasks:
  clean:
    desc: Clean the build directory
    cmds:
      - rm -rf {{.ROOT_DIR}}/build/*

  # Perftest build tasks
  perf:
    desc: Build the performance test binary
    dir: cmd/perf
    requires:
      vars: [ arch ]
    vars:
      FILE: "{{if eq OS `windows`}}perftest.exe{{else}}perftest{{end}}"
    env:
      CGO_ENABLED: 1
      GOARCH: "{{.arch}}"
    cmds:
      - |
        go build -o "{{.ROOT_DIR}}/build/{{.FILE}}"
        {{if .isPackage}}7z a -tzip -mx=9 "{{.ROOT_DIR}}/build/perftest_{{OS}}_{{.arch}}.zip" "{{.ROOT_DIR}}/build/{{.FILE}}"{{end}}

  # GUI build tasks
  gui:
    desc: Build the GUI version of the app
    dir: cmd/gui
    requires:
      vars: [ arch ]
    vars:
      OLD_FILE: "{{if eq OS `darwin`}}opai.app{{else}}{{if eq OS `windows`}}opai.exe{{else}}opai{{end}}{{end}}"
      NEW_FILE: "{{if eq OS `darwin`}}OpenPhotoAI.app{{else}}{{if eq OS `windows`}}OpenPhotoAI.exe{{else}}OpenPhotoAI{{end}}{{end}}"
    env:
      CGO_ENABLED: 1
      PRODUCTION: true
      ARCH: "{{.arch}}"
    cmds:
      - |
        {{if eq OS "darwin"}}
          wails3 package ARCH={{.arch}}
        {{else}}
          wails3 build ARCH={{.arch}}
        {{end}}

        rm -rf "{{.ROOT_DIR}}/build/{{.NEW_FILE}}"
        mkdir -p "{{.ROOT_DIR}}/build"
        mv "{{.ROOT_DIR}}/cmd/gui/bin/{{.OLD_FILE}}" "{{.ROOT_DIR}}/build/{{.NEW_FILE}}"

        {{if .isPackage}}
          7z a -tzip -mx=9 "{{.ROOT_DIR}}/build/opai-gui_{{OS}}_{{.arch}}.zip" "{{.ROOT_DIR}}/build/{{.NEW_FILE}}"
        {{end}}

  package:
    desc: Build and pack in .zip files
    requires:
      vars: [ archs ]
    cmds:
      - |
        for arch in {{.archs}}; do
          task gui arch=$arch isPackage=true
        done