// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

export function OpenFileDialog(): $CancellablePromise<types$0.DialogFile[]> {
    return $Call.ByID(3411436064).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = types$0.DialogFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
