// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Destroy(): $CancellablePromise<void> {
    return $Call.ByID(3681465753);
}

export function GetImage(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(2406933080, filePath).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}

export function ProcessImage(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(3391347795, filePath).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}
