allowBuilds:
  '@firebase/util': true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@vitejs/plugin-react@6.1.0'
  - vite@8.2.2
  - '@wailsio/runtime@3.0.0-beta.10'
onlyBuiltDependencies:
  - '@firebase/util'
  - '@tailwindcss/oxide'
  - esbuild
  - protobufjs
