// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DialogFile {
    "Path": string;
    "Hash": string;

    /** Creates a new DialogFile instance. */
    constructor($$source: Partial<DialogFile> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Hash" in $$source)) {
            this["Hash"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DialogFile instance from a string or object.
     */
    static createFrom($$source: any = {}): DialogFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DialogFile($$parsedSource as Partial<DialogFile>);
    }
}
