// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as services$0 from "../../../../../gui/services/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as types$0 from "../../../../../gui/types/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "app:FilesDropped": types$0.File[];
            "app:download": services$0.DownloadProgress;
            "app:export": services$0.ExportUpdate;
            "app:progress": services$0.InferenceProgress;
        }
    }
}
