// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ImageFormat describes the type of image used.
 */
export enum ImageFormat {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * Constants for supported image formats.
     */
    FormatAvif = 0,
    FormatBmp = 1,
    FormatGif = 2,
    FormatHeic = 3,
    FormatJpeg = 4,
    FormatPng = 5,
    FormatTiff = 6,
    FormatWebp = 7,
};
