// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Destroy(): $CancellablePromise<void> {
    return $Call.ByID(623737359);
}

export function Initialize(): $CancellablePromise<void> {
    return $Call.ByID(3426585365);
}

export function IsOutdated(): $CancellablePromise<boolean> {
    return $Call.ByID(2990044471);
}

export function Version(): $CancellablePromise<string> {
    return $Call.ByID(3408143585);
}
