// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Initialize(): $CancellablePromise<$models.SupportedEPs> {
    return $Call.ByID(3426585365).then(($result: any) => {
        return $$createType0($result);
    });
}

export function IsOutdated(): $CancellablePromise<boolean> {
    return $Call.ByID(2990044471);
}

export function Version(): $CancellablePromise<string> {
    return $Call.ByID(3408143585);
}

// Private type creation functions
const $$createType0 = $models.SupportedEPs.createFrom;
