// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CleanRegistry unloads every model currently held in memory, so the next enhancement rebuilds them - that's how a
 * change to the AI processor takes effect, since the registry is keyed by operation ID only.
 * 
 * It destroys the native ONNX sessions right away, so the frontend must not call it while an enhancement, an export or
 * a face detection is running: freeing a session mid-inference kills the whole app. The frontend holds the call back
 * until nothing is in flight (see `runWhenIdle` in stores/jobs.ts).
 */
export function CleanRegistry(): $CancellablePromise<void> {
    return $Call.ByID(3767199187);
}

/**
 * GetLogsPath returns the absolute path to the application's log file. It mirrors how shared.SetupLogging builds the
 * path so the two stay in sync.
 */
export function GetLogsPath(): $CancellablePromise<string> {
    return $Call.ByID(2055045473);
}

export function Initialize(): $CancellablePromise<$models.SupportedEPs> {
    return $Call.ByID(3426585365).then(($result: any) => {
        return $$createType0($result);
    });
}

export function IsOutdated(): $CancellablePromise<boolean> {
    return $Call.ByID(2990044471);
}

export function Version(): $CancellablePromise<string> {
    return $Call.ByID(3408143585);
}

// Private type creation functions
const $$createType0 = $models.SupportedEPs.createFrom;
