// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$1 from "../../github.com/vegidio/open-photo-ai/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * ExportImage runs the operations named by opIds and writes the result to outputPath. Unless overwrite is set, an
 * existing file is left alone and a "_N" suffix is added instead (see getOutputPath).
 * 
 * quality is 1-100 and only affects the lossy formats; see utils.EncodeImage. Progress is reported through
 * EventAppExport rather than the return value, keyed by file.Hash.
 */
export function ExportImage(file: types$0.File, outputPath: string, ep: types$1.ExecutionProvider, overwrite: boolean, format: types$1.ImageFormat, quality: number, params: types$0.InferenceParams, ...opIds: string[]): $CancellablePromise<void> {
    return $Call.ByID(1308095068, file, outputPath, ep, overwrite, format, quality, params, opIds);
}

/**
 * GetImage loads an image and returns it JPEG-encoded, together with its width and height.
 * 
 * size caps the longest dimension, resizing proportionally; 0 returns the original dimensions. crop is only applied
 * when size == 0 (the full-resolution preview), since the thumbnails are never cropped.
 */
export function GetImage(filePath: string, size: number, crop: types$0.CropInfo): $CancellablePromise<[string, number, number]> {
    return $Call.ByID(2406933080, filePath, size, crop).then(($result: any) => {
        $result[0] = $Create.ByteSlice($result[0]);
        return $result;
    });
}

/**
 * ProcessImage runs the operations named by opIds (see utils.IdsToOperations for the ID format) and returns the
 * result JPEG-encoded for preview, together with its width and height.
 */
export function ProcessImage(filePath: string, ep: types$1.ExecutionProvider, params: types$0.InferenceParams, ...opIds: string[]): $CancellablePromise<[string, number, number]> {
    return $Call.ByID(3391347795, filePath, ep, params, opIds).then(($result: any) => {
        $result[0] = $Create.ByteSlice($result[0]);
        return $result;
    });
}

/**
 * SuggestEnhancements analyzes an image and returns the enhancement types worth applying to it.
 */
export function SuggestEnhancements(filePath: string): $CancellablePromise<types$1.ModelType[]> {
    return $Call.ByID(808798930, filePath).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
