// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Destroy(): $CancellablePromise<void> {
    return $Call.ByID(3681465753);
}

/**
 * GetImage loads an image from the specified file path and optionally resizes it.
 * 
 * # Parameters:
 *   - filePath: The path to the image file to load
 *   - size: The target size for the longest dimension of the image. If size is 0, the image is returned at its original
 *     dimensions. If size > 0, the image is resized proportionally so that its longest dimension (width or height)
 *     equals the specified size, using Lanczos resampling for high quality.
 * 
 * # Returns:
 *   - []byte: The image data encoded as PNG bytes (lossless)
 *   - int: The width of the image
 *   - int: The height of the image
 *   - error: An error if the image cannot be loaded, processed, or encoded
 */
export function GetImage(filePath: string, size: number): $CancellablePromise<[string, number, number]> {
    return $Call.ByID(2406933080, filePath, size).then(($result: any) => {
        $result[0] = $Create.ByteSlice($result[0]);
        return $result;
    });
}

export function ProcessImage(filePath: string, ...opIds: string[]): $CancellablePromise<[string, number, number]> {
    return $Call.ByID(3391347795, filePath, opIds).then(($result: any) => {
        $result[0] = $Create.ByteSlice($result[0]);
        return $result;
    });
}
