// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DownloadProgress is the payload of EventAppDownload. Emitted while a required runtime dependency
 * (ONNX Runtime, CUDA, cuDNN, TensorRT) is being fetched.
 */
export class DownloadProgress {
    "dependency": string;
    "percent": number;

    /** Creates a new DownloadProgress instance. */
    constructor($$source: Partial<DownloadProgress> = {}) {
        if (!("dependency" in $$source)) {
            this["dependency"] = "";
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadProgress($$parsedSource as Partial<DownloadProgress>);
    }
}

/**
 * ExportUpdate is the payload of EventAppExport. One event stream serves every file in the export
 * queue; subscribers filter by Hash.
 * 
 * Value is overloaded by State: while RUNNING it is a 0.0–1.0 progress ratio; on COMPLETED it is
 * the final file size in bytes. The frontend export row formats it accordingly.
 */
export class ExportUpdate {
    "hash": string;
    "state": string;
    "value": number;

    /** Creates a new ExportUpdate instance. */
    constructor($$source: Partial<ExportUpdate> = {}) {
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportUpdate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportUpdate($$parsedSource as Partial<ExportUpdate>);
    }
}

/**
 * InferenceProgress is the payload of EventAppProgress. Emitted as each model step within a
 * processing pipeline advances; Name identifies the sub-operation.
 */
export class InferenceProgress {
    "name": string;
    "progress": number;

    /** Creates a new InferenceProgress instance. */
    constructor($$source: Partial<InferenceProgress> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InferenceProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): InferenceProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InferenceProgress($$parsedSource as Partial<InferenceProgress>);
    }
}

/**
 * ProviderFallback is the payload of EventAppFallback. Emitted when the selected AI processor couldn't be used - a
 * GPU driver that is broken or too old, a GPU without enough free memory - and inference was downgraded to the CPU.
 * Only the first downgrade since the models were last loaded is emitted, so the user isn't told the same thing on
 * every operation, but a different processor that also fails is reported again.
 */
export class ProviderFallback {
    "provider": string;

    /** Creates a new ProviderFallback instance. */
    constructor($$source: Partial<ProviderFallback> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderFallback instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderFallback {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderFallback($$parsedSource as Partial<ProviderFallback>);
    }
}

export class SupportedEPs {
    "CUDA": boolean;
    "TensorRT": boolean;
    "CoreML": boolean;

    /** Creates a new SupportedEPs instance. */
    constructor($$source: Partial<SupportedEPs> = {}) {
        if (!("CUDA" in $$source)) {
            this["CUDA"] = false;
        }
        if (!("TensorRT" in $$source)) {
            this["TensorRT"] = false;
        }
        if (!("CoreML" in $$source)) {
            this["CoreML"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SupportedEPs instance from a string or object.
     */
    static createFrom($$source: any = {}): SupportedEPs {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SupportedEPs($$parsedSource as Partial<SupportedEPs>);
    }
}

/**
 * UnsupportedFiles is the payload of EventAppUnsupportedFiles. Emitted when a drag-and-drop included files the
 * decoder can't read. Only the base names are sent: the frontend renders the message, so the wording - and its plural
 * form, which the "len == 1" test here could only ever get right for English - lives in the i18n catalog instead.
 */
export class UnsupportedFiles {
    "names": string[];

    /** Creates a new UnsupportedFiles instance. */
    constructor($$source: Partial<UnsupportedFiles> = {}) {
        if (!("names" in $$source)) {
            this["names"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnsupportedFiles instance from a string or object.
     */
    static createFrom($$source: any = {}): UnsupportedFiles {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("names" in $$parsedSource) {
            $$parsedSource["names"] = $$createField0_0($$parsedSource["names"]);
        }
        return new UnsupportedFiles($$parsedSource as Partial<UnsupportedFiles>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
