// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SupportedEPs {
    "CUDA": boolean;
    "TensorRT": boolean;
    "CoreML": boolean;

    /** Creates a new SupportedEPs instance. */
    constructor($$source: Partial<SupportedEPs> = {}) {
        if (!("CUDA" in $$source)) {
            this["CUDA"] = false;
        }
        if (!("TensorRT" in $$source)) {
            this["TensorRT"] = false;
        }
        if (!("CoreML" in $$source)) {
            this["CoreML"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SupportedEPs instance from a string or object.
     */
    static createFrom($$source: any = {}): SupportedEPs {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SupportedEPs($$parsedSource as Partial<SupportedEPs>);
    }
}
