// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OsService exposes the handful of host-platform facts and actions the frontend needs. Every exported method here is
 * callable from JS through the generated bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetArch returns the CPU architecture this build is running on, as a Go GOARCH value ("arm64", "amd64").
 */
export function GetArch(): $CancellablePromise<string> {
    return $Call.ByID(2217750252);
}

/**
 * GetOS returns the operating system this build is running on, as a Go GOOS value ("darwin", "windows", "linux").
 * The frontend uses it to pick platform-specific wording and shortcuts.
 */
export function GetOS(): $CancellablePromise<string> {
    return $Call.ByID(60039734);
}

/**
 * RevealInFileManager opens the platform file manager with path selected — Finder on macOS, Explorer on Windows —
 * so the user can get to an exported image or the log file without typing the path.
 */
export function RevealInFileManager(path: string): $CancellablePromise<void> {
    return $Call.ByID(4171282367, path);
}
