// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function RevealDirInFileManager(path: string): $CancellablePromise<void> {
    return $Call.ByID(96567492, path);
}

export function RevealInFileManager(path: string): $CancellablePromise<void> {
    return $Call.ByID(4171282367, path);
}
